#!/usr/bin/env python
from ase.io import read, write
from ase.io.vasp import read_vasp_xdatcar
from ase.visualize import view

x = read_vasp_xdatcar(file='XDATCAR', index=slice(None))
view(x)
#write('test.traj',x)
